package main

var Actions = []Action{
{Hash: "sessionHash_1", Scenario: "Scenario1" },
{Hash: "sessionHash_1", Scenario: "Scenario2" },
{Hash: "sessionHash_1", Scenario: "Scenario3" },
{Hash: "sessionHash_1", Scenario: "Scenario4" },
{Hash: "sessionHash_1", Scenario: "Number", Attr:"123456789" },
{Hash: "sessionHash_2", Scenario: "Scenario1" },
{Hash: "sessionHash_2", Scenario: "Scenario2" },
{Hash: "sessionHash_2", Scenario: "Scenario3" },
{Hash: "sessionHash_2", Scenario: "Scenario4" },
{Hash: "sessionHash_2", Scenario: "Number", Attr:"123456789" },
{Hash: "sessionHash_2", Scenario: "Scenario1" },
{Hash: "sessionHash_2", Scenario: "Scenario2" },
{Hash: "sessionHash_2", Scenario: "Scenario3" },
{Hash: "sessionHash_2", Scenario: "Scenario4" },
{Hash: "sessionHash_2", Scenario: "Number", Attr:"123456789" },
{Hash: "sessionHash_2", Scenario: "Scenario1" },
{Hash: "sessionHash_2", Scenario: "Scenario2" },
{Hash: "sessionHash_2", Scenario: "Scenario3" },
{Hash: "sessionHash_2", Scenario: "Scenario4" },
{Hash: "sessionHash_2", Scenario: "Number", Attr:"123456789" },
{Hash: "sessionHash_3", Scenario: "Scenario3" },
{Hash: "sessionHash_3", Scenario: "Scenario2" },
{Hash: "sessionHash_3", Scenario: "Scenario3" },
{Hash: "sessionHash_3", Scenario: "Scenario4" },
{Hash: "sessionHash_3", Scenario: "Number", Attr:"123456789" },
{Hash: "sessionHash_4", Scenario: "Scenario1" },
{Hash: "sessionHash_4", Scenario: "Scenario2" },
{Hash: "sessionHash_4", Scenario: "Scenario3" },
{Hash: "sessionHash_4", Scenario: "Scenario4" },
{Hash: "sessionHash_4", Scenario: "Number", Attr:"987654321" },
{Hash: "sessionHash_5", Scenario: "Scenario5" },
{Hash: "sessionHash_5", Scenario: "Scenario2" },
{Hash: "sessionHash_5", Scenario: "Scenario3" },
{Hash: "sessionHash_5", Scenario: "Scenario4" },
{Hash: "sessionHash_5", Scenario: "Number", Attr:"987654321" },
{Hash: "sessionHash_6", Scenario: "Scenario1" },
{Hash: "sessionHash_6", Scenario: "Scenario2" },
{Hash: "sessionHash_6", Scenario: "Scenario3" },
{Hash: "sessionHash_6", Scenario: "Scenario4" },
{Hash: "sessionHash_7", Scenario: "Number", Attr:"098765" },

}